# Generated by Django 5.1.6 on 2025-03-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflixapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='image',
        ),
        migrations.AddField(
            model_name='movies',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
