# Generated by Django 5.1.6 on 2025-03-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_otp_expires_at_otp_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_code',
            new_name='otp',
        ),
    ]
